# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "cocoapods 安装"
  lane :setup do
    cocoapods
  end

  desc "截图"
  lane :screenshots do
    capture_screenshots(
    	workspace: "Candy.xcworkspace", 
    	scheme: "CandyUITests"
    )
    frameit
  end

  desc "创建 Release ipa"
  lane :build do
      build_app(
      	scheme: "Candy",
        workspace: "Candy.xcworkspace",
        include_bitcode: true,
        xcargs: "-allowProvisioningUpdates",
      	silent: true,
		    clean: true,
		    configuration: "Release" # Defaults to 'Release' can set up 'Debug'
  	  )
  end

  desc "部署 AppStore"
  lane :release do
    deliver
  end

  desc "增加 build num"
  lane :increment_build do
    increment_build_number
    commit_version_bump
  end

  desc "部署 AppStore"
  lane :deploy_apple_store do
    screenshots
    build
    release
  end

  desc "证书"
  lane :certificates do
    match(
      git_branch: "hdsonic@sohu.com", 
      username: "704861917@qq.com"
    )
  end

end
